version: '3'

services:
  postgres-node-1:
    container_name: postgres-node-1
    image: bitnami/postgresql-repmgr:latest
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=mydatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=postgres-node-1
      - REPMGR_NODE_NAME=postgres-node-1
      - REPMGR_NODE_NETWORK_NAME=postgres-node-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_PARTNER_NODES=postgres-node-1,postgres-node-2
      - BITNAMI_DEBUG=true
    ports:
      - "5432:5432"
    volumes:
      - postgres-node-1-data:/bitnami/postgresql

  postgres-node-2:
    container_name: postgres-node-2
    image: bitnami/postgresql-repmgr:latest
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=mydatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=postgres-node-1
      - REPMGR_NODE_NAME=postgres-node-2
      - REPMGR_NODE_NETWORK_NAME=postgres-node-2
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_PARTNER_NODES=postgres-node-1,postgres-node-2
      - BITNAMI_DEBUG=true
    depends_on:
      - postgres-node-1
    ports:
      - "5433:5432"
    volumes:
      - postgres-node-2-data:/bitnami/postgresql

  grafana-node-1:
    container_name: grafana-node-1
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - grafana-node-1-data:/var/lib/grafana
    depends_on:
      - haproxy

  grafana-node-2:
    container_name: grafana-node-2
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - grafana-node-2-data:/var/lib/grafana
    depends_on:
      - haproxy

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - grafana-node-1
      - grafana-node-2

  haproxy:
    image: haproxy:latest
    ports:
      - "5434:5432"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - postgres-node-1
      - postgres-node-2

volumes:
  postgres-node-1-data:
  postgres-node-2-data:
  grafana-node-1-data:
  grafana-node-2-data: