apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres-node-1:5432
    database: mydatabase
    user: myuser
    password: mypassword
    jsonData:
      sslmode: "disable"

